# Generated by Django 3.2.5 on 2021-11-21 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_gspcdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gspcdata',
            name='volume',
            field=models.BigIntegerField(),
        ),
    ]
